#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Aug 03, 2023 02:30:21 PM EDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
import cv2
import numpy as np
import os
import threading
from tkinter.constants import *
from tkinter import filedialog
global vid_current
vid_current = -2

import Lightning1

_debug = True

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Lightning1.Toplevel1(_top1)
    _w1.Btn_input.configure(command=open_folder_i)
    _w1.Btn_output.configure(command=open_folder_o)
    _w1.Btn_start.configure(command=start_button)
    _w1.Btn_cancel.configure(command=cancel)
    _w1.Lbl_vid_num.configure(text='''0''')
    _w1.Lbl_video_tot.configure(text='''0''')
    _w1.Lbl_frame_tot.configure(text='''0''')
    _w1.Lbl_frm_num.configure(text='''0''')
    _w1.Lbl_pro.configure(text=''' ''')
    _w1.top.resizable(False,  False)
    
    root.mainloop()
    


def cancel():
    global running
    running = False
    

def quit(*args):
    print('Lightning1_support.quit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()
    sys.exit()

def open_folder_i():
    folder_path = filedialog.askdirectory() 
    
    if folder_path:
        _w1.Txt_input.insert(tk.END, folder_path)
    else:
        print("No folder selected")

def open_folder_o():
    folder_path = filedialog.askdirectory() 
    
    if folder_path:
        _w1.Txt_Output.insert(tk.END, folder_path)
    else:
        print("No folder selected")

def start_button():
    st = threading.Thread(target=start_processing)
    st.start()
def start_processing():
    global running
    running = True
    def update_labels(vid_current, frame_count, frame_total,vid_total):
        _w1.Lbl_vid_num.configure(text=vid_current)
        _w1.Lbl_frm_num.configure(text=frame_count)
        _w1.Lbl_frame_tot.configure(text=frame_total)
        _w1.Lbl_video_tot.configure(text=vid_total)
        _top1.update_idletasks()
    
    
    def calculate_brightness(frame):
        # Convert the frame to grayscale for brightness calculation
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        return np.mean(gray_frame)
    
    

    def save_brighter_frames(input_path, output_path,vid_current, threshold, input_folder_path):
        cap = cv2.VideoCapture(input_path)
        _w1.Lbl_pro.configure(text="Processing")
        num_files = 0
        for root, dirs, files in os.walk(input_folder_path):
            num_files += len(files)
        vid_total = (num_files)
        vid_current += 1
        frame_total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        # Read the first frame to initialize the variables
        ret, prev_frame = cap.read()
        if not ret:
            return

        darkest_frame_brightness = calculate_brightness(prev_frame)
        
        #threshold = darkest_frame_brightness / darkest_frame_brightness ** 1.7 * 35

        frame_count = 0
        video_name = os.path.splitext(os.path.basename(input_path))[0]  # Move video_name declaration here
        while True:
            
            ret, frame = cap.read()
            if not ret:
                break

            if not running:
                break
                

            current_brightness = calculate_brightness(frame)

            if darkest_frame_brightness == 0:
                darkest_frame_brightness = .1
            else:
                if current_brightness < darkest_frame_brightness:
                    darkest_frame_brightness = current_brightness

            thres_percent = round(current_brightness / darkest_frame_brightness, 2)
            df = round(darkest_frame_brightness, 5)
            cf = round(current_brightness, 5)
            th = round(threshold, 2)
            
            if current_brightness >= darkest_frame_brightness * threshold:
                output_frame_path = os.path.join(output_path, f"{video_name}_frame_{frame_count}_{thres_percent}_{df}_{cf}_{th}.jpg")
                cv2.imwrite(output_frame_path, frame)

            
            
            
            frame_count += 1
            frame_pro = frame_count / frame_total * 100
            vid_pro = vid_current / vid_total * 100
            update_labels(vid_current, frame_count, frame_total,vid_total)
            _w1.TPro_frame.configure(value=frame_pro)
            _w1.TPro_vid.configure(value=vid_pro)
            
        cap.release()
        if running:
            vid_current += 1
            frame_count += 1
            frame_pro = frame_count / frame_total * 100
            vid_pro = vid_current / vid_total * 100
            _w1.TPro_frame.configure(value=frame_pro)
            _w1.TPro_vid.configure(value=vid_pro)
            _w1.Lbl_pro.configure(text="Done")
            update_labels(vid_current, frame_count, frame_total,vid_total)
    
    

    input_folder_path = _w1.Txt_input.get(1.0, tk.END).strip()
    output_folder_path = _w1.Txt_Output.get(1.0, tk.END).strip()
    threshold = float(_w1.Ent_thres.get())
    vid_current = -2

    
    # Process every video in the input folder
    for filename in os.listdir(input_folder_path):
        vid_current += 1
        if filename.endswith(".MOV") or filename.endswith(".mp4"):
            input_video_path = os.path.join(input_folder_path, filename)
            save_brighter_frames(input_video_path, output_folder_path, vid_current, threshold, input_folder_path)
    

if __name__ == '__main__':
    Lightning1.start_up()




