#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Aug 08, 2023 08:40:16 PM EDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import Lightning1_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran:
       return
    style = ttk.Style()
    if sys.platform == "win32":
       style.theme_use('winnative')
    style.configure('.',background=_bgcolor)
    style.configure('.',foreground=_fgcolor)
    style.configure('.',font='TkDefaultFont')
    style.map('.',background =
       [('selected', _compcolor), ('active',_ana2color)])
    if _bgmode == 'dark':
       style.map('.',foreground =
         [('selected', 'white'), ('active','white')])
    else:
       style.map('.',foreground =
         [('selected', 'black'), ('active','black')])
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x484+205+135")
        top.minsize(600, 484)
        top.maxsize(600, 484)
        top.resizable(1,  1)
        top.title("Lightning")
      #  top.iconbitmap("lightning.ico")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        

        self.top = top

        self.Btn_input = tk.Button(self.top)
        self.Btn_input.place(relx=0.717, rely=0.145, height=29, width=37)
        self.Btn_input.configure(activebackground="beige")
        self.Btn_input.configure(activeforeground="black")
        self.Btn_input.configure(background="#d9d9d9")
        self.Btn_input.configure(compound='left')
        self.Btn_input.configure(disabledforeground="#a3a3a3")
        self.Btn_input.configure(foreground="#000000")
        self.Btn_input.configure(highlightbackground="#d9d9d9")
        self.Btn_input.configure(highlightcolor="black")
        self.Btn_input.configure(pady="0")
        self.Btn_input.configure(text='''...''')
        self.Ent_thres = tk.Entry(self.top)
        self.Ent_thres.place(relx=0.033, rely=0.434, height=30, relwidth=0.257)
        self.Ent_thres.configure(background="white")
        self.Ent_thres.configure(disabledforeground="#a3a3a3")
        self.Ent_thres.configure(font="TkFixedFont")
        self.Ent_thres.configure(foreground="#000000")
        self.Ent_thres.configure(highlightbackground="#d9d9d9")
        self.Ent_thres.configure(highlightcolor="black")
        self.Ent_thres.configure(insertbackground="black")
        self.Ent_thres.configure(selectbackground="#c4c4c4")
        self.Ent_thres.configure(selectforeground="black")
        self.Ent_thres_tooltip = \
        ToolTip(self.Ent_thres, '''Sensitivity threshold for lightning detection. Lower values catch more flashes; 6.0 is a good starting point.''')

        self.Txt_input = tk.Text(self.top)
        self.Txt_input.place(relx=0.033, rely=0.145, relheight=0.06
                , relwidth=0.673)
        self.Txt_input.configure(background="white")
        self.Txt_input.configure(font="TkTextFont")
        self.Txt_input.configure(foreground="black")
        self.Txt_input.configure(highlightbackground="#d9d9d9")
        self.Txt_input.configure(highlightcolor="black")
        self.Txt_input.configure(insertbackground="black")
        self.Txt_input.configure(pady="5")
        self.Txt_input.configure(selectbackground="#c4c4c4")
        self.Txt_input.configure(selectforeground="black")
        self.Txt_input.configure(wrap="word")
        self.Txt_Output = tk.Text(self.top)
        self.Txt_Output.place(relx=0.033, rely=0.289, relheight=0.06
                , relwidth=0.673)
        self.Txt_Output.configure(background="white")
        self.Txt_Output.configure(font="TkTextFont")
        self.Txt_Output.configure(foreground="black")
        self.Txt_Output.configure(highlightbackground="#d9d9d9")
        self.Txt_Output.configure(highlightcolor="black")
        self.Txt_Output.configure(insertbackground="black")
        self.Txt_Output.configure(pady="5")
        self.Txt_Output.configure(selectbackground="#c4c4c4")
        self.Txt_Output.configure(selectforeground="black")
        self.Txt_Output.configure(wrap="word")
        self.Btn_output = tk.Button(self.top)
        self.Btn_output.place(relx=0.717, rely=0.289, height=29, width=37)
        self.Btn_output.configure(activebackground="beige")
        self.Btn_output.configure(activeforeground="black")
        self.Btn_output.configure(background="#d9d9d9")
        self.Btn_output.configure(compound='left')
        self.Btn_output.configure(disabledforeground="#a3a3a3")
        self.Btn_output.configure(foreground="#000000")
        self.Btn_output.configure(highlightbackground="#d9d9d9")
        self.Btn_output.configure(highlightcolor="black")
        self.Btn_output.configure(pady="0")
        self.Btn_output.configure(text='''...''')
        self.Lbl_input = tk.Label(self.top)
        self.Lbl_input.place(relx=0.033, rely=0.083, height=21, width=294)
        self.Lbl_input.configure(activebackground="#f9f9f9")
        self.Lbl_input.configure(anchor='w')
        self.Lbl_input.configure(background="#d9d9d9")
        self.Lbl_input.configure(compound='left')
        self.Lbl_input.configure(disabledforeground="#a3a3a3")
        self.Lbl_input.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Lbl_input.configure(foreground="#000000")
        self.Lbl_input.configure(highlightbackground="#d9d9d9")
        self.Lbl_input.configure(highlightcolor="black")
        self.Lbl_input.configure(text='''Choose your video input folder.''')
        self.Lbl_output = tk.Label(self.top)
        self.Lbl_output.place(relx=0.033, rely=0.227, height=21, width=314)
        self.Lbl_output.configure(activebackground="#f9f9f9")
        self.Lbl_output.configure(anchor='w')
        self.Lbl_output.configure(background="#d9d9d9")
        self.Lbl_output.configure(compound='left')
        self.Lbl_output.configure(disabledforeground="#a3a3a3")
        self.Lbl_output.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Lbl_output.configure(foreground="#000000")
        self.Lbl_output.configure(highlightbackground="#d9d9d9")
        self.Lbl_output.configure(highlightcolor="black")
        self.Lbl_output.configure(text='''Choose your frame output folder.''')
        self.Lbl_thres = tk.Label(self.top)
        self.Lbl_thres.place(relx=0.033, rely=0.372, height=21, width=214)
        self.Lbl_thres.configure(activebackground="#f9f9f9")
        self.Lbl_thres.configure(anchor='w')
        self.Lbl_thres.configure(background="#d9d9d9")
        self.Lbl_thres.configure(compound='left')
        self.Lbl_thres.configure(disabledforeground="#a3a3a3")
        self.Lbl_thres.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Lbl_thres.configure(foreground="#000000")
        self.Lbl_thres.configure(highlightbackground="#d9d9d9")
        self.Lbl_thres.configure(highlightcolor="black")
        self.Lbl_thres.configure(text='''Set your lightning threshold.''')
        self.Btn_start = tk.Button(self.top)
        self.Btn_start.place(relx=0.033, rely=0.558, height=24, width=67)
        self.Btn_start.configure(activebackground="beige")
        self.Btn_start.configure(activeforeground="black")
        self.Btn_start.configure(background="#d9d9d9")
        self.Btn_start.configure(compound='left')
        self.Btn_start.configure(disabledforeground="#a3a3a3")
        self.Btn_start.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Btn_start.configure(foreground="#000000")
        self.Btn_start.configure(highlightbackground="#d9d9d9")
        self.Btn_start.configure(highlightcolor="black")
        self.Btn_start.configure(pady="0")
        self.Btn_start.configure(text='''Start''')
        self.Btn_cancel = tk.Button(self.top)
        self.Btn_cancel.place(relx=0.167, rely=0.558, height=24, width=67)
        self.Btn_cancel.configure(activebackground="beige")
        self.Btn_cancel.configure(activeforeground="black")
        self.Btn_cancel.configure(background="#d9d9d9")
        self.Btn_cancel.configure(compound='left')
        self.Btn_cancel.configure(disabledforeground="#a3a3a3")
        self.Btn_cancel.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Btn_cancel.configure(foreground="#000000")
        self.Btn_cancel.configure(highlightbackground="#d9d9d9")
        self.Btn_cancel.configure(highlightcolor="black")
        self.Btn_cancel.configure(pady="0")
        self.Btn_cancel.configure(text='''Cancel''')
        self.Lbl_video_tot = tk.Label(self.top)
        self.Lbl_video_tot.place(relx=0.868, rely=0.868, height=21, width=64)
        self.Lbl_video_tot.configure(activebackground="#f9f9f9")
        self.Lbl_video_tot.configure(anchor='w')
        self.Lbl_video_tot.configure(background="#d9d9d9")
        self.Lbl_video_tot.configure(compound='left')
        self.Lbl_video_tot.configure(disabledforeground="#a3a3a3")
        self.Lbl_video_tot.configure(font="-family {Segoe UI} -size 9")
        self.Lbl_video_tot.configure(foreground="#000000")
        self.Lbl_video_tot.configure(highlightbackground="#d9d9d9")
        self.Lbl_video_tot.configure(highlightcolor="black")
        self.Lbl_video_tot.configure(justify='left')
        self.Lbl_video_tot.configure(text='''Video Total''')
        self.Lbl_vid_num = tk.Label(self.top)
        self.Lbl_vid_num.place(relx=0.747, rely=0.868, height=21, width=64)
        self.Lbl_vid_num.configure(activebackground="#f9f9f9")
        self.Lbl_vid_num.configure(anchor='e')
        self.Lbl_vid_num.configure(background="#d9d9d9")
        self.Lbl_vid_num.configure(compound='left')
        self.Lbl_vid_num.configure(disabledforeground="#a3a3a3")
        self.Lbl_vid_num.configure(foreground="#000000")
        self.Lbl_vid_num.configure(highlightbackground="#d9d9d9")
        self.Lbl_vid_num.configure(highlightcolor="black")
        self.Lbl_vid_num.configure(justify='right')
        self.Lbl_vid_num.configure(text='''Video#''')
        self.Lbl_frame_tot = tk.Label(self.top)
        self.Lbl_frame_tot.place(relx=0.868, rely=0.95, height=21, width=64)
        self.Lbl_frame_tot.configure(activebackground="#f9f9f9")
        self.Lbl_frame_tot.configure(anchor='w')
        self.Lbl_frame_tot.configure(background="#d9d9d9")
        self.Lbl_frame_tot.configure(compound='left')
        self.Lbl_frame_tot.configure(disabledforeground="#a3a3a3")
        self.Lbl_frame_tot.configure(font="-family {Segoe UI} -size 9")
        self.Lbl_frame_tot.configure(foreground="#000000")
        self.Lbl_frame_tot.configure(highlightbackground="#d9d9d9")
        self.Lbl_frame_tot.configure(highlightcolor="black")
        self.Lbl_frame_tot.configure(justify='left')
        self.Lbl_frame_tot.configure(text='''Frame Total''')
        self.Lbl_frm_num = tk.Label(self.top)
        self.Lbl_frm_num.place(relx=0.747, rely=0.95, height=21, width=64)
        self.Lbl_frm_num.configure(activebackground="#f9f9f9")
        self.Lbl_frm_num.configure(anchor='e')
        self.Lbl_frm_num.configure(background="#d9d9d9")
        self.Lbl_frm_num.configure(compound='left')
        self.Lbl_frm_num.configure(disabledforeground="#a3a3a3")
        self.Lbl_frm_num.configure(foreground="#000000")
        self.Lbl_frm_num.configure(highlightbackground="#d9d9d9")
        self.Lbl_frm_num.configure(highlightcolor="black")
        self.Lbl_frm_num.configure(justify='right')
        self.Lbl_frm_num.configure(text='''Frame#''')
        self.Lbl_f_sep = tk.Label(self.top)
        self.Lbl_f_sep.place(relx=0.85, rely=0.95, height=21, width=14)
        self.Lbl_f_sep.configure(activebackground="#f9f9f9")
        self.Lbl_f_sep.configure(anchor='w')
        self.Lbl_f_sep.configure(background="#d9d9d9")
        self.Lbl_f_sep.configure(compound='left')
        self.Lbl_f_sep.configure(disabledforeground="#a3a3a3")
        self.Lbl_f_sep.configure(foreground="#000000")
        self.Lbl_f_sep.configure(highlightbackground="#d9d9d9")
        self.Lbl_f_sep.configure(highlightcolor="black")
        self.Lbl_f_sep.configure(text='''/''')
        self.Lbl_vid_sep = tk.Label(self.top)
        self.Lbl_vid_sep.place(relx=0.85, rely=0.868, height=21, width=14)
        self.Lbl_vid_sep.configure(activebackground="#f9f9f9")
        self.Lbl_vid_sep.configure(anchor='w')
        self.Lbl_vid_sep.configure(background="#d9d9d9")
        self.Lbl_vid_sep.configure(compound='left')
        self.Lbl_vid_sep.configure(disabledforeground="#a3a3a3")
        self.Lbl_vid_sep.configure(foreground="#000000")
        self.Lbl_vid_sep.configure(highlightbackground="#d9d9d9")
        self.Lbl_vid_sep.configure(highlightcolor="black")
        self.Lbl_vid_sep.configure(text='''/''')
        self.Lbl_pro = tk.Label(self.top)
        self.Lbl_pro.place(relx=0.033, rely=0.723, height=21, width=134)
        self.Lbl_pro.configure(activebackground="#f9f9f9")
        self.Lbl_pro.configure(anchor='w')
        self.Lbl_pro.configure(background="#d9d9d9")
        self.Lbl_pro.configure(compound='left')
        self.Lbl_pro.configure(disabledforeground="#a3a3a3")
        self.Lbl_pro.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Lbl_pro.configure(foreground="#000000")
        self.Lbl_pro.configure(highlightbackground="#d9d9d9")
        self.Lbl_pro.configure(highlightcolor="black")
        self.Lbl_pro.configure(text='''Processing / Done''')
        _style_code()
        self.TPro_frame = ttk.Progressbar(self.top)
        self.TPro_frame.place(relx=0.017, rely=0.95, relwidth=0.7, relheight=0.0
                , height=22)
        self.TPro_frame.configure(length="420")
        self.TPro_vid = ttk.Progressbar(self.top)
        self.TPro_vid.place(relx=0.017, rely=0.868, relwidth=0.7, relheight=0.0
                , height=22)
        self.TPro_vid.configure(length="420")
        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

from time import time, localtime, strftime
class ToolTip(tk.Toplevel):
    """ Provides a ToolTip widget for Tkinter. """
    def __init__(self, wdgt, msg=None, msgFunc=None, delay=0.5,
                 follow=True):
        self.wdgt = wdgt
        self.parent = self.wdgt.master
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        self.withdraw()
        self.overrideredirect(True)
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        self.msg = tk.Message(self, textvariable=self.msgVar, bg=_bgcolor,
                   fg=_fgcolor, font="TkDefaultFont",
                   aspect=1000)
        self.msg.grid()
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')
    def spawn(self, event=None):
        self.visible = 1
        self.after(int(self.delay * 1000), self.show)
    def show(self):
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()
    def move(self, event):
        self.lastMotion = time()
        if self.follow is False:
            self.withdraw()
            self.visible = 1
        self.geometry('+%i+%i' % (event.x_root + 20, event.y_root - 10))
        try:
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)
    def hide(self, event=None):
        self.visible = 0
        self.withdraw()
    def update(self, msg):
        self.msgVar.set(msg)
    def configure(self, **kwargs):
        backgroundset = False
        foregroundset = False
        # Get the current tooltip text just in case the user doesn't provide any.
        current_text = self.msgVar.get()
        # to clear the tooltip text, use the .update method
        if 'debug' in kwargs.keys():
            debug = kwargs.pop('debug', False)
            if debug:
                for key, value in kwargs.items():
                    print(f'key: {key} - value: {value}')
        if 'background' in kwargs.keys():
            background = kwargs.pop('background')
            backgroundset = True
        if 'bg' in kwargs.keys():
            background = kwargs.pop('bg')
            backgroundset = True
        if 'foreground' in kwargs.keys():
            foreground = kwargs.pop('foreground')
            foregroundset = True
        if 'fg' in kwargs.keys():
            foreground = kwargs.pop('fg')
            foregroundset = True

        fontd = kwargs.pop('font', None)
        if 'text' in kwargs.keys():
            text = kwargs.pop('text')
            if (text == '') or (text == "\n"):
                text = current_text
            else:
                self.msgVar.set(text)
        reliefd = kwargs.pop('relief', 'flat')
        justifyd = kwargs.pop('justify', 'left')
        padxd = kwargs.pop('padx', 1)
        padyd = kwargs.pop('pady', 1)
        borderwidthd = kwargs.pop('borderwidth', 2)
        wid = self.msg      # The message widget which is the actual tooltip
        if backgroundset:
            wid.config(bg=background)
        if foregroundset:
            wid.config(fg=foreground)
        wid.config(font=fontd)
        wid.config(borderwidth=borderwidthd)
        wid.config(relief=reliefd)
        wid.config(justify=justifyd)
        wid.config(padx=padxd)
        wid.config(pady=padyd)
#                   End of Class ToolTip

def start_up():
    Lightning1_support.main()

if __name__ == '__main__':
    Lightning1_support.main()




